#!/bin/sh
# require wvHtml (doc)
# require pandoc (docx/odt)
# require libreoffice (xls/xlsx/ods)

set -e

if [ $# -eq 0 ]; then
  echo "Need argument(s): doc(x)/odt/xls(x)/ods file" 1>&2
  exit 1
fi

i="$1"
basename="${i##*/}"
filename="${basename%.*}"
tmpdir=/tmp/convertdoc ;

if [ -f "${i}" ]
then
    ext="${i##*.}"
    case $ext in
        doc) wvHtml "${i}" - | pandoc -f html -t html ;;
        docx|odt) \
            pandoc "${i}" -t html ;;
            # libreoffice --headless --convert-to doc \
            #             --outdir ${tmpdir} "${i}" > /dev/null ;
            # wvHtml ${tmpdir}/"${filename}.doc" - | pandoc -f html -t html ;;
        xls|xlsx|ods) \
            libreoffice --headless --convert-to html \
                        --outdir ${tmpdir} "${i}" > /dev/null ;
            cat ${tmpdir}/"${filename}.html" ;
            rm -f ${tmpfile} ;;
       *) ;;
   esac
fi
