#!/bin/sh
# require antiword (.doc), pandoc (.docx) and pdftotext (.pdf)

if [ $# -eq 0 ]; then
  echo "Need argument(s): doc, docx or pdf file(s)" 1>&2
  exit 1
fi

for i in $*
do
    if [ -f ${i} ]
    then
       ext="${i##*.}"
       case $ext in
           doc)  antiword -w 0 ${i} ;;
           docx) pandoc -t plain ${i} ;;
           pdf ) pdftotext -raw ${i} - ;;
           *)    ;;
       esac
    fi
done

